### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by TheLegendHimself** [maelhos/InductorGen#1]
Hey i saw your comment on:
https://risencrypto.github.io/QuadraticSieve/
and was wondering if you could help me with my implementation?
I am struggling with the matrix / how to solve it (maybe i am even building it wrong)
If you are happy to help here is my mail: Paul.Mayer1987@protonmail.com
if you dont want to just close the issue i will leave you alone

**Comment by maelhos** [comment]
Im contacting you...
